### DISCUSSION TITLE
Recommendation for running Laravel Websocket

### DISCUSSION THREAD

**Discussion by jericopulvera** [serversideup/docker-php#100] [Q&A] [answered]
https://beyondco.de/docs/laravel-websockets/basic-usage/starting

Is there a way define a supervisord within Dockerfile without having conflict with the base image?

or will it be okay to just add `php artisan websockets:serve` inside the Dockerfile?

**Comment by jaydrogers** [comment, marked as answer]
Using Docker + S6 Overlay + Supervisor can cause your image to get too "crowded". To compare, it's like having "too many chefs in the kitchen".

I have not attempted to use Beyond Code's Laravel Web sockets, but I assume it would work like a queue.

1. Do not use supervisor, S6 Overlay will monitor the process(es) for you
2. Run the websockets server as its own container (like a queue): https://github.com/serversideup/docker-php#running-a-laravel-queue

**I have not tested this**, but here is an example of what I would do to get started:
```YML
version: '3'
services:
  php:
    image: my/laravel-app
    environment:
      PHP_POOL_NAME: "my-app_php"

  websockets:
    image: my/laravel-app
    # Switch to "webuser" before running `php artisan`
    # Declare command in list manner for environment variable expansion
    command: ["su", "webuser", "-c", "php artisan websockets:serve"]
    environment:
      PHP_POOL_NAME: "my-app_websockets"
```

Let me know if that works for you. Hope this helps!
