### DISCUSSION TITLE
Queue worker dies after a while.

### DISCUSSION THREAD

**Discussion by jericopulvera** [serversideup/docker-php#106] [Q&A] [answered]
I have deployed a queue worker via AWS Copilot Backend Service. It does work but it consistently dies after a while.

<img width="359" alt="image" src="https://user-images.githubusercontent.com/23246308/209618446-05bc3946-fa59-471b-ad3b-923b405ea7c2.png">

```
[27-Dec-2022 05:54:37] NOTICE: Terminating ...
--
[27-Dec-2022 05:54:37] NOTICE: exiting, bye-bye!
```

Dockerfile
```Dockerfile
# syntax = docker/dockerfile:experimental

# Default to PHP 8.1, but we attempt to match
# Valid version values are PHP 7.4+
ARG PHP_VERSION=8.0
FROM serversideup/php:${PHP_VERSION}-fpm-nginx-v2.0.2:latest as base

# PHP_VERSION needs to be repeated here
# See https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
ARG PHP_VERSION

# See https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
RUN apt-get update && apt-get install -y \
    git curl zip unzip rsync ca-certificates vim htop cron \
    php${PHP_VERSION}-mysql php${PHP_VERSION}-bcmath \
    php${PHP_VERSION}-swoole php${PHP_VERSION}-xml php${PHP_VERSION}-mbstring \
    php${PHP_VERSION}-intl php${PHP_VERSION}-memcache php${PHP_VERSION}-memcached \
    jpegoptim optipng pngquant gifsicle webp \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html
COPY . /var/www/html

RUN composer install --optimize-autoloader --no-dev \
    && mkdir -p storage/logs \
    && php artisan optimize:clear \
    && chown -R webuser:webgroup /var/www/html \
    && sed -i 's/protected \$proxies/protected \$proxies = "*"/g' app/Http/Middleware/TrustProxies.php \
    && echo "MAILTO=\"\"\n* * * * * webuser /usr/bin/php /var/www/html/artisan schedule:run" > /etc/cron.d/laravel \
    && rm -rf /etc/cont-init.d/* 

ENV SSL_MODE=off

CMD ["su", "webuser", "-c", "php artisan queue:work --tries=3"]
```
What outputs this Notice?

**Comment by jaydrogers** [comment, marked as answer]
This will happen if `exit 1` is returned. I wonder if this is an application specific error in your `RecalclateOrdersJob`?

Unfortunately I won't be able to debug unless if I have repeatable steps to reproduce and diagnose the issue.

**Reply by jericopulvera** [reply]
I see then it must be on the container health check. 

https://aws.github.io/copilot-cli/docs/manifest/backend-service/

```yml
image:
  # Docker build arguments. For additional overrides: https://aws.github.io/copilot-cli/docs/manifest/backend-service/#image-build
  build: Dockerfile.worker
  port: 80
  healthcheck:
    command: ["CMD-SHELL", "curl -f http://localhost:80/ping || exit 1"]
    retries: 10
    interval: 21s
    timeout: 20s
    start_period: 30s
```

That must mean that /ping do not respond when it's processing a job. Does moving to -fpm only without nginx be better?
