### DISCUSSION TITLE
Xdebug with fpm-nginx

### DISCUSSION THREAD

**Discussion by emilebourquin** [serversideup/docker-php#176] [Show and tell]
To get Xdebug working with the fpm-nginx image, I did this:

If your _docker-compose.yml_ file starts like this:
```
version: '3.8'

services:
   nginx_php:
      image: serversideup/php:8.2-fpm-nginx
...
```

replace that part with:
```
version: '3.8'

services:
   nginx_php:
      build:
         dockerfile: fpm-nginx_xdebug.dockerfile
         args:
            - PHP_VERSION=${PHP_VERSION}
      image: serversideup/php:${PHP_VERSION}-fpm-nginx_xdebug
...
```

In the same directory as _docker-compose.yml_ , create a file named _fpm-nginx_xdebug.dockerfile_ , and put this in it:
```
ARG PHP_VERSION

FROM serversideup/php:${PHP_VERSION}-fpm-nginx

RUN apt-get update \
    && apt-get install -y php-dev php-pear \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/* \
    && pecl install xdebug

ARG PHP_VERSION

# Set PHP_INI_DIR for docker-php-ext-enable to use
ENV PHP_INI_DIR=/etc/php/${PHP_VERSION}/fpm

ADD https://raw.githubusercontent.com/docker-library/php/master/docker-php-ext-enable /usr/bin/docker-php-ext-enable
RUN chmod u+x /usr/bin/docker-php-ext-enable

ARG PHP_VERSION

RUN docker-php-ext-enable xdebug \
    && echo "xdebug.mode=debug" >> /etc/php/${PHP_VERSION}/fpm/conf.d/docker-php-ext-xdebug.ini \
# -- EITHER --
    && echo "xdebug.start_with_request=yes" >> /etc/php/${PHP_VERSION}/fpm/conf.d/docker-php-ext-xdebug.ini \
# -- OR --
#    && echo "xdebug.start_with_request=trigger" >> /etc/php/${PHP_VERSION}/fpm/conf.d/docker-php-ext-xdebug.ini \
#    && echo "xdebug.trigger_value=PHPSTORM" >> /etc/php/${PHP_VERSION}/fpm/conf.d/docker-php-ext-xdebug.ini \
# Use a browser debugging extension from https://www.jetbrains.com/help/phpstorm/2023.1/browser-debugging-extensions.html
# -- END EITHER OR --
    && echo "xdebug.client_port=9003" >> /etc/php/${PHP_VERSION}/fpm/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.client_host=host.docker.internal" >> /etc/php/${PHP_VERSION}/fpm/conf.d/docker-php-ext-xdebug.ini

RUN rm /usr/bin/docker-php-ext-enable \
    && apt-get purge -y php-dev php-pear

# Expose port 9003 for Xdebug
EXPOSE 9003
```

and start your Docker containers with this command:
```
PHP_VERSION=8.2 docker compose up nginx_php -d
```

Note: If the lines:
```
ADD https://raw.githubusercontent.com/docker-library/php/master/docker-php-ext-enable /usr/bin/docker-php-ext-enable
RUN chmod u+x /usr/bin/docker-php-ext-enable
```
freak you out, you could always manually copy the contents of https://raw.githubusercontent.com/docker-library/php/master/docker-php-ext-enable to a local file named _docker-php-ext-enable_ , have a look at it, and instead of the ADD command, use:
```
COPY docker-php-ext-enable /usr/bin/docker-php-ext-enable
```
