### DISCUSSION TITLE
I noticed syslog are being ignored

### DISCUSSION THREAD

**Discussion by agarzon-orangerine** [serversideup/docker-php#178] [General]
This is not necessarily a good thing, specially with virtualization. Basically the syslog messages coming from any framework like Laravel or cakephp are being ignored.

**Comment by jaydrogers** [comment]
Sorry for the delayed response... I was on holiday for two weeks.

Can you explain further? Or show a repeatable example with "Actual Results" vs. "Expected Results"?

I have the logs going to STDOUT & STDERR so they appear in your Docker Logging system: https://github.com/serversideup/docker-php/blob/07143a6e3d9dd3d83b3fc07d6505616bab9ded0a/src/fpm/etc/php/fpm/pool.d/y-override-php-defaults.conf#L11-L12

**Reply by agarzon-orangerine** [reply]
You are right, somehow another setup I have using cakephp is not showing stderr but a simple setup and just made to show you, it did worked.

For the record:

compose.yml
```yaml
services:
  webserver:
    image: serversideup/php:8.2-fpm-apache
    ports:
      - 80:80
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - SSL_MODE=off
      - AUTORUN_ENABLED=false
    volumes:
      - ./:/var/www/html
```

index.php

```php
<?php

$a = 5 / 0; # it gonna fail!

``` 
![image](https://github.com/serversideup/docker-php/assets/75088937/08dc4e1c-21f3-4f74-9d11-5d7d36314185)

So, I'll close this.
