### DISCUSSION TITLE
Getting slow behaviour

### DISCUSSION THREAD

**Discussion by ijpatricio** [serversideup/docker-php#208] [Q&A] [answered]
Hey @jaydrogers 

It's not my first time reporting this, but I'm getting it again.

Via Forge, I have set a Hetzer CPX21 (x86_64) 3core, 4 RAM, and it's a production project.
After Forge provisions the thing, I install docker, the website, and configure nginx with a proxy_pass to Docker's service port.

The first one is with docker-php, and right now, it's at a point where I can even give you access to everything if you want to debug yourself.

When I got suspicious about the speed, I installed a second website from the same repo, even using the same database,  but with Native nginx+fpm.

1. Docker PHP
https://forum.unitedbycode.com/
https://forum.unitedbycode.com/forum

2. Native Forge's nginx+fpm
https://io.unitedbycode.com/
https://io.unitedbycode.com/forum

Try to access them and navigate. It's a fork of laravel.io, just plain install, not seeded.

Inside the machine I run
```
time curl  http://localhost:8002/api/articles
```
Which is an API endpoint, without providing any authentication, so it should be the one of the quickest endpoints, right?

But no, I consistently get 1.4-1.5 seconds.

Below, I'll leave the relevant configurations.

Please let me know what I'm doing wrong.

Nginx config:
```
    location / {
        #try_files $uri $uri/ /index.php?$query_string;
        proxy_pass http://localhost:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```

The compose file:
```
services:
    webapp:
        build:
            context: .
            dockerfile: ./docker/prod/Dockerfile
        image: unitedbycode/forum
        environment:
            PUID: 1000
            PGID: 1000
            SSL_MODE: off
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8001}:80'
        volumes:
            - '.:/var/www/html'

```

The Dockerfile
```
FROM node:20 as static-assets

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build


FROM serversideup/php:8.2-fpm-nginx

RUN apt-get update

# MySQL
RUN apt-get install -y mysql-client

RUN apt-get -y autoremove && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

COPY --from=static-assets --chown=9999:9999 /app/public/build ./public/build

RUN echo "alias ll='ls -al'" >>/etc/bash.bashrc
RUN echo "alias a='php artisan'" >>/etc/bash.bashrc
RUN echo "alias mfs='php artisan migrate:fresh --seed'" >>/etc/bash.bashrc
RUN echo "alias cda='composer dump-autoload'" >>/etc/bash.bashrc
RUN echo "alias run='./scripts/run'" >>/etc/bash.bashrc

```

**Comment by tomschlick** [comment]
@ijpatricio were you able to find a solution to this? I'm experiencing some of the same using the combined PHP+FPM+Nginx image currently.

**Comment by ijpatricio** [comment]
Hey @tomschlick still no.
But hey, good times ahead, @jaydrogers is on the verge of launching totally new images, based off the official PHP as base! 😄 

The ubuntu22 flavor with s6 and nginx+fpm will still continue to exist, and it still makes sense IMO, so not sure if it will remain the same base, and potentially, the same issue.

Now we're 2 that can make tests/experiments. What do you think, @jaydrogers ?

**Reply by jaydrogers** [reply]
My biggest thing is being able to reproduce. Honestly, I haven't looked into this since I have been focused on the new version of the containers.

I've been running these images with similar configurations for years and I haven't had any issues. Tracing down the problem will be the biggest effort.

If you both can work to figure out a solution, that would be a huge help. I want to make sure this issue does not exist in the new containers as well.

**Reply by tomschlick** [reply]
I spent some time on this last night and was able to narrow it down to something in Laravel. If I create a `public/test.php` file with `Hello World` the execution is as low as `2ms`. 

If I hit a Hello World endpoint in Laravel (all middleware disabled) it is no less than `700ms` to get through the `booting` event of the framework.

This doesn't happen when I host it on a Vapor (using the docker runtime) or on Laravel Forge (not a container). So I think it's something either in the config of PHP-FPM or something similar. I'll be looking into that tonight to see if I can resolve it. If it's something that can be improved in the docker config by default I'll open a PR.

**Reply by ijpatricio** [reply]
That's a nice find!

To add some insights, I've been building my images based on ubuntu:22.04, with Supervisor, and with this setup also no issues.
Same for using multiple containers, having nginx and fpm with dedicated containers...

**Reply by jaydrogers** [reply]
Thanks for diving in deep on this guys. I greatly appreciate the help!!

**Reply by jaydrogers** [reply]
@tomschlick If you have steps to reproduce that would be great.

I'm hoping to have a new image for you to test with soon. I say if we can get the steps to reproduce on the current images, we should test those steps on the new images.

**Comment by ijpatricio** [comment]
I do have a reproducible setup.
repo is: https://github.com/unitedbycode/laravel.io/blob/production/docker-compose.prod.yml

https://io.unitedbycode.com/ => laravel.io repo directly on nginx+fpm, by Forge
https://forum.unitedbycode.com => same repo, but mounted with a compose and proxy:

turn on inspector and check timings

https://github.com/unitedbycode/laravel.io/blob/production/docker-compose.prod.yml
```
services:
    webapp:
        build:
            context: .
            dockerfile: ./docker/prod/Dockerfile
        image: unitedbycode/forum
        environment:
            PUID: 1000
            PGID: 1000
            SSL_MODE: off
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8001}:80'
        volumes:
            - '.:/var/www/html'
```


```
 location / {
        #try_files $uri $uri/ /index.php?$query_string;
        proxy_pass http://localhost:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```
