### DISCUSSION TITLE
How to output as a file : `docker logs  docker-compose-lnmp-php_fpm-1`

### DISCUSSION THREAD

**Discussion by q2333gh** [serversideup/docker-php#324] [Q&A] [answered]
When using `docker logs docker-compose-lnmp-php_fpm-1`
the logs not display real-time. 

How to bind this log as a file between host and container 

to make it just like nginx-container:
```conf
server {

  listen 80;
  listen [::]:80;
  server_name localhost;

  charset utf-8;

####
  access_log /var/log/nginx/access.log main;
  error_log /var/log/nginx/error.log error;
####

...
```

```yml
  nginx:
    image: nginx:1.20.1
    volumes:
      ## config
      - ./my_nginx/configs/conf.d:/etc/nginx/conf.d
      ## log #### by doing this can dynamicly show logs####
      - ./my_nginx/logs:/var/log/nginx
      ## site datas:
      - ./www:/var/www
      # - ./www:/www
    networks:
      - lnmp
    depends_on:
      - php_fpm
    expose:
      - "80"
    ports:
      # left:host , right: container
      - "801:80"
```
