### DISCUSSION TITLE
Add/remove S6 services

### DISCUSSION THREAD

**Discussion by terax6669** [serversideup/docker-php#378] [Ideas & Feature Requests]
## 👉 Describe the problem
I want to run a single container that will handle all background tasks, like scheduler and queue for Laravel.

## 👥 Problem evidence & reach
Everyone? O_o
![image](https://github.com/serversideup/docker-php/assets/19204073/9f7b9576-43be-4d28-8ec8-0d21ae858dd8)

### Unnecessary services - nginx and php-fpm (#373)
There is no way to disable them. [Docs](https://serversideup.net/open-source/docker-php/docs/laravel/laravel-queue) suggest running a separate container for each background task so we're running unnecessary services in all non-web containers.

### Adding custom services
[Docs](https://serversideup.net/open-source/docker-php/docs/guide/using-s6-overlay#customizing-the-initialization-process) suggest we might create additional s6 services:
> S6 Overlay has a number of options to write our own service script and properly time everything.

However there is no example of how to do that. I personally find S6's documentation extremely chaotic. It'd be nice to include an example for easy starting point.

### Laravel support?
Maybe we could get some automation for example by passing some config for serversideup image startup scripts?
Seems very easy to automate the scheduler, but much more complex for queues, because you have to define a number of queue workers, a bunch of parameters which could potentially be different for every worker.

Current yaml:
```
services:
  app:
    image: my-image:latest
    ports:
      - 8080:8080
    user: ${USER_ID}:${GROUP_ID}

  app_queue_1:
    image: my-image:latest
    user: ${USER_ID}:${GROUP_ID}
    command:
      [
        "php",
        "/var/www/html/artisan",
        "queue:work",
        "--queue=high,default"
        "--sleep=3",
        "--tries=3",
        "--max-time=3600",
      ]

  app_queue_2:
    image: my-image:latest
    user: ${USER_ID}:${GROUP_ID}
    command:
      [
        "php",
        "/var/www/html/artisan",
        "queue:work",
        "--queue=default"
        "--sleep=3",
        "--tries=3",
        "--max-time=3600",
      ]

  app_schedule:
    image: ["${IMAGE_NAME_APP}:${BRANCH:-latest}"](my-image:latest)
    user: ${USER_ID}:${GROUP_ID}
    command: ["php", "/var/www/html/artisan", "schedule:work"]
```

Imaginary yaml:
```
services:
  app:
    image: my-image:latest
    ports:
      - 8080:8080
    user: ${USER_ID}:${GROUP_ID}

  app_artisan:
    image: my-image:latest
    user: ${USER_ID}:${GROUP_ID}
    environment:
      S6_DISABLE_WEBSERVER: 1
      S6_ENABLE_LARAVEL_SCHEDULER: 1
      S6_ENABLE_LARAVEL_QUEUE: 1
      LARAVEL_QUEUE_COUNT: 2
      LARAVEL_QUEUE_TYPES: high,default|default
      ...
```
## 🥰 Describe the "impact" on users?
Lower resource usage. Especially since every container starts with nginx and php-fpm running.

## 💯 How do we validate the problem is solved?
Users are able to customize what services are running.
