### DISCUSSION TITLE
Unable to Access PHP 8.3 Docker Container on 127.0.0.1

### DISCUSSION THREAD

**Discussion by anhducbkhn** [serversideup/docker-php#396] [Q&A] [answered]
I am doing some testing with PHP 8.3 image.
This is my docker-compose-local.yml file

**my local:**
- Ubuntu 20.04.6 LTS
- docker version: 27.0.3

```yaml
version: '3.8'
services:
  php:
    image: serversideup/php:8.3-fpm-nginx
    ports:
      - 80:80
    environment:
      SSL_MODE: "off"
    volumes:
      - .:/var/www/html
```

This is my code folder

```
public
  └──index.php
docker-compose-local.yml
```

When I run command `docker compose -f docker-compose-local.yml up`, I'm unable to access the container via the browser using the address http://127.0.0.1.

I am using old version of serversideup/php:8.2-fpm-nginx and it still working.

Please help me identify where I might be going wrong.
