### DISCUSSION TITLE
Error after composer install

### DISCUSSION THREAD

**Discussion by manusiakemos** [serversideup/docker-php#432] [Q&A] [answered]
i need help
container always exit after composer install
![image](https://github.com/user-attachments/assets/fcd36080-4b4f-406a-9e25-7fe397d72239)

- docker-compose
```yaml
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:8080"
    # command: bash -c "composer install --no-interaction"
    volumes:
      - ./:/var/www/html
    networks:
      - laravel
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      SSL_MODE: "off"
      PHP_UPLOAD_MAX_FILE_SIZE: 4M
      PHP_POST_MAX_SIZE: 4M
      PHP_MEMORY_LIMIT: 256M
      PHP_DATE_TIMEZONE: "Asia/Makassar"
      AUTORUN_ENABLED: true
      PHP_OPCACHE_ENABLE: 1
      PHP_FPM_POOL_NAME: "app"
networks:
  laravel:
    driver: bridge
```

- Dockerfile
```yaml
############################################
# Base Image
############################################
FROM serversideup/php:8.3-fpm-nginx AS base

#set working directory
WORKDIR /var/www/html
ENV PHP_OPCACHE_ENABLE=1
ENV COMPOSER_ALLOW_SUPERUSER=1

# Switch to root before installing our PHP extensions
USER root
RUN install-php-extensions intl gd exif pdo pdo_mysql zip

############################################
# Production Image
############################################
FROM base AS deploy
COPY --chown=www-data:www-data . /var/www/html
USER www-data
ENTRYPOINT ["bash", "-c", "composer install --no-interaction --optimize-autoloader"]
EXPOSE 8080
```
