### DISCUSSION TITLE
How to Properly Execute Composer Commands at Container Startup

### DISCUSSION THREAD

**Discussion by omarherri** [serversideup/docker-php#446] [Q&A]
I'm looking for guidance on how to effectively run Composer commands during container startup instead of during the image build process. Here's the background:

**Context:**
I am working with a Laravel application, and I'm using Docker to manage the environment. The project requires running specific Laravel commands such as` composer install` and `php artisan optimize`. However, these commands in my case depend on external services like Redis.

**Current Issue:**
When building the Docker image, Redis is not available, and thus, the build process fails with the following error:
`php_network_getaddresses: getaddrinfo for redis failed: Name or service not known`

My Current Docker Setup:

**Docker Compose File (docker-compose.yml):**
```
services:
  laravel-mailcoach:
    container_name: laravel-mailcoach
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel:mailcoach
    volumes:
      - './storage/app:/var/www/html/storage/app'
    networks:
      - traefik_network
    environment:
      PHP_OPCACHE_ENABLE: 1
    labels:
      - "traefik.enable=true"
      ...
    depends_on:
      - redis

  schedule:
    image: laravel:mailcoach
    command: [ "php", "/var/www/html/artisan", "schedule:work" ]
    networks:
      - traefik_network
    depends_on:
      - redis
      - laravel-mailcoach

  horizon:
    image: laravel:mailcoach
    command: [ "php", "/var/www/html/artisan", "horizon" ]
    networks:
      - traefik_network
    depends_on:
      - redis
      - laravel-mailcoach

  redis:
    image: 'redis:alpine'
    volumes:
      - 'redis_data:/data'
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true

volumes:
  redis_data:
```

**Dockerfile:**
```
FROM serversideup/php:8.3-fpm-nginx

ENV S6_CMD_WAIT_FOR_SERVICES=1

COPY --chmod=755 ./entrypoint.d/ /etc/entrypoint.d/

# Switch to root so we can do root things
USER root

# Install the intl extension with root permissions
RUN install-php-extensions exif gd imagick \
    && install-php-extensions bcmath mbstring intl

# Install composer
WORKDIR /var/www/html

# Copy the entire app to the container
COPY . .

# Fix permissions for Laravel's storage and cache directories
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache \
    && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache

RUN docker-php-serversideup-s6-init

# Drop back to our unprivileged user
USER www-data
```
**99-entrypoint.sh**
```
#!/bin/sh
composer install --no-dev --prefer-dist --optimize-autoloader
php artisan optimize
php artisan storage:link
```

**Desired Outcome:**
Instead of running Composer commands (like php artisan optimize or composer install) during the Docker image build process, I would like these commands to be executed at container startup. This way, Redis and other services are fully available, and the Laravel app can properly interact with them.
