### DISCUSSION TITLE
ERROR: unable to bind listening socket for address '9000': Address in use. From what I can tell, it's not.

### DISCUSSION THREAD

**Discussion by onairmarc** [serversideup/docker-php#457] [Q&A]
I'm new to Docker, so please forgive me if the answer is obvious. I'm running into an issue when running `docker compose up`. Three of the four services appear to be running just fine, but the main service `app` which is the one that is running `php-fpm` keeps crashing with the error `ERROR: unable to bind listening socket for address '9000': Address in use`.

The most obvious answer is to check what is running on port 9000. As I'm running this locally on Mac for now, I ran
`sudo lsof -i :9000` and it returned no results. I then tried shelling into the container itself with `docker exec -it epp-core-app sh` but was met with this error: `Error response from daemon: Container {HASH REDACTED} is restarting, wait until the container is running.` Because of this, I was unable check what else might have been using that port from within the container.

I've included logs and my configuration files below for reference. I appreciate any guidance you may have

### Logs
```shell
epp-core-app        | 👉 [NOTICE]: Improve PHP performance by setting PHP_OPCACHE_ENABLE=1 (recommended for production).
epp-core-app        | ℹ️ NOTICE (init-webserver-config): /etc/nginx/nginx.conf already exists, so we'll use the existing file.
epp-core-app        | ℹ️ NOTICE (init-webserver-config): /etc/nginx/site-opts.d/http.conf already exists, so we'll use the existing file.
epp-core-app        | ℹ️ NOTICE (init-webserver-config): /etc/nginx/site-opts.d/https.conf already exists, so we'll use the existing file.
epp-core-app        | ℹ️ NOTICE (init-webserver-config): /etc/nginx/conf.d/default.conf already exists, so we'll use the provided configuration.
epp-core-app        | [06-Oct-2024 13:15:33] NOTICE: fpm is running, pid 88
epp-core-app        | [06-Oct-2024 13:15:33] NOTICE: ready to handle connections
epp-core-app        | ✅ NGINX + PHP-FPM is running correctly.
epp-core-app        | [06-Oct-2024 13:15:34] NOTICE: Failed implicitly binding to ::, retrying with 0.0.0.0
epp-core-app        | [06-Oct-2024 13:15:34] ERROR: unable to bind listening socket for address '9000': Address in use (98)
epp-core-app        | [06-Oct-2024 13:15:34] ERROR: FPM initialization failed
epp-core-app        | [06-Oct-2024 13:15:34] NOTICE: Terminating ...
epp-core-app        | [06-Oct-2024 13:15:34] NOTICE: exiting, bye-bye!
epp-core-app exited with code 78
```

### Dockerfile

```Dockerfile
FROM serversideup/php:8.3-fpm-nginx-alpine
LABEL authors="marcbeinder"

# Ensure we are running as root for package installations
USER root

# Use the build arguments to change the UID
# and GID of www-data while also changing
# the file permissions for NGINX
RUN docker-php-serversideup-set-id www-data 82:82 && \
    \
    # Update the file permissions for our NGINX service to match the new UID/GID
    docker-php-serversideup-set-file-permissions --owner 82:82 --service nginx

# Install system dependencies and clear apk cache afterward
RUN apk update && apk add \
    git \
    curl \
    libpng-dev \
    oniguruma-dev \
    libxml2-dev \
    zip \
    unzip && \
    rm -rf /var/cache/apk/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create the home directory for the user and set ownership
RUN mkdir -p /home/www-data/.composer && \
    chown -R www-data:www-data /home/www-data

# Set the working directory
WORKDIR /var/www

# Switch to non-root user after package installations
USER www-data

# Define the default command for PHP-FPM
CMD ["php-fpm"]
```

### docker-compose.yml

```yml
services:
    nginx:
        image: nginx:1.17-alpine
        container_name: epp-core-nginx
        restart: unless-stopped
        ports:
            - "80:8080"
        volumes:
            - ./:/var/www
            - ./.config/nginx:/etc/nginx/conf.d
        networks:
            - epp-core-net

    app:
        build:
            args:
                userId: 1000
                groupId: 1000
            context: ./
            dockerfile: Dockerfile
        image: epp-core
        container_name: epp-core-app
        restart: unless-stopped
        stop_signal: SIGTERM
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - epp-core-net

    scheduler:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                userId: 1000
                groupId: 1000
        image: epp-core
        container_name: epp-core-scheduler
        restart: unless-stopped
        stop_signal: SIGTERM
        working_dir: /var/www/
        command: [ "php", "/var/www/artisan", "schedule:work" ]
        volumes:
            - ./:/var/www
        networks:
            - epp-core-net

    queue:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                userId: 1000
                groupId: 1000
        image: epp-core
        container_name: epp-core-queue
        restart: unless-stopped
        stop_signal: SIGTERM
        working_dir: /var/www/
        command: [ "php", "/var/www/artisan", "queue:work" ]
        volumes:
            - ./:/var/www
        networks:
            - epp-core-net

networks:
    epp-core-net:
        driver: bridge
```

### nginx.conf

```conf
server {
    listen 80;
    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/public;

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }
}
```

**Comment by jaydrogers** [comment]
That's really strange you're seeing that error because you're not exposing 9000 on your host.

Our of curiosity, have you seen our project Spin? It might help with a lot of what you're trying to achieve. Instead of running NGINX → FPM-NGINX, we have a nice template to give you Traefik → FPM-NGINX on Alpine if it meets your project requirements. No pressure to change to Spin, but just wanted to share it so it's on your radar: https://serversideup.net/open-source/spin

If you want to test something out, you could install Spin then run `spin new laravel` to create a new project then `spin up` to see if that works.

In regards to the port 9000 being used, my gut points to this:
```
epp-core-app        | [06-Oct-2024 13:15:34] NOTICE: Failed implicitly binding to ::, retrying with 0.0.0.0
epp-core-app        | [06-Oct-2024 13:15:34] ERROR: unable to bind listening socket for address '9000': Address in use (98)
```

I wonder if this is an IPv6 thing? Are you running macOS Sequoia by any chance?

**Comment by onairmarc** [comment]
Apologies for the delayed reply, this weekend is moving weekend for me! I have seen spin only briefly as a result of my research but I have not had the chance to take a deep look yet. I can try to give spin a shot and try the `spin new laravel` command sometime this week.

I did make some progress by switching the image to `serversideup/php:8.3-unit`. When using the `unit` image, everything seems to start up properly but when I navigate to `http://localhost:8080` I get a `502 Bad Gateway` error. I tried both `http` and `https` just to be sure. I do have Laravel Herd installed on this machine and did verify that Herd was not running as I figured that might cause some issues.

Yes, I am currently running macOS Sequoia 15.01 on a 2019 MacBook Pro.

It's probably going to be something super obvious resulting in a glorious facepalm. 🤓🤦🏻‍♂️

**Reply by jaydrogers** [reply]
Hahaha! No problem. I hope the move went well!

My gut feeling is I just hope it's not a Sequoia update with IPv6. I am still running Sonoma at the moment, but I will upgrade one of my non-production machines to use Sequoia and will test it out 😅

**Reply by onairmarc** [reply]
Wonderful! I'm still setting up the home-lab after the move (soooo. many. boxes.), but once that's done I'll be in a spot to begin testing again!

**Reply by jaydrogers** [reply]
Hey @onairmarc,

Hope you're not buried in boxes 😃

Just wanted to let you know that I upgraded my home machine to macOS 15.0.1 and it worked perfectly with Spin, so it's not a Sequoia issue:

![Screenshot 2024-10-16 at 19 40 31@2x](https://github.com/user-attachments/assets/61e7fae8-b178-4804-ab03-7a578d9bd4b1)

### Some things I noticed in your Dockerfile

```Dockerfile
# You're calling fpm-nginx-alpine, which is a good variation to run
FROM serversideup/php:8.3-fpm-nginx-alpine

# You're running this, which isn't needed because www-data is ID of 82 by default
RUN docker-php-serversideup-set-id www-data 82:82 && \
        docker-php-serversideup-set-file-permissions --owner 82:82 --service nginx

# You're copying composer (which we already have set up for you
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# You're dropping to php-fpm (which I would just run the `fpm` variation if you need FPM only)
CMD ["php-fpm"]
```

### Your Docker compose file also has some interesting things in it

```yml
    scheduler:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                # You're setting an ID of 1000 but this never gets called in your Dockerfile file
                userId: 1000
                groupId: 1000
```

I have a feeling this could be a permission issue. 

From the configs I see above, I would expect this config to not work. I hate to repeat myself, but looking at this again it seems like Spin is going to answer a lot of your questions. I just spent hundreds of hours to get it dialed in and it seems like it's going to match your exact use case.

Let me know if you have any other questions!

**Reply by onairmarc** [reply]
Oh I'm definitely buried in boxes 😂.

I did have a chance to read through some more Spin documentation and I'm liking what I'm seeing except for the deploy story. I'd much prefer to not have the automated pipeline ssh into each box.

Assuming that the Spin deploy story is optional, I should have time to do a deep dive into Spin this weekend!

**Reply by onairmarc** [reply]
Also, thanks for pointing out my config errors! I'm totally new to docker and have absolutely no idea how it works. Somehow I've made it 10 years without ever needing to touch it until now 🤓

**Reply by jaydrogers** [reply]
No problem! Let me know if you have any more questions.

> I'd much prefer to not have the automated pipeline ssh into each box

I'm interested to hear on why you wouldn't want this and if there are any alternate approaches to this. If security is a concern about giving a private key to GitHub, then locking down SSH to a static IP with a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners) is your best bet.

At the end of the day, regardless of what is doing a deployment -- no matter if it is an API key, an SSH key, or authenticated GitHub app, something will need administrative permissions to run a deployment on your container orchestrator.

Hope the move is going well. I was just telling my friend the other day, "Moving sucks, but it's totally worth it!" 😃 Hopefully you'll get to that "worth it" part soon 😆

**Reply by onairmarc** [reply]
It's not really a security thing, it more of a maintainability thing. We use Digital Ocean App Platform for a lot of our applications so the deployment story is already solved there. 

That coupled with the use of Terraform, we really don't have the need for Spin to manage deploys; at least for right now. It may make more sense in some future projects and some infrastructure changes we want to make, but for the first iteration of containerizing everything, it just doesn't make sense for now.

I'm getting close to it being worth it, it's just very time consuming! 😂

**Reply by jaydrogers** [reply]
Ahh okay, makes sense!

Yes, that's the beautiful thing about Spin. You don't have to use it for deployments if you don't want to. If you don't want to use it to manage your production deployment, you just delete `docker-compose.prod.yml` 🪄✨

I made sure everything was flexible so you can use it when you need it

**Reply by onairmarc** [reply]
Love it! I'll let you know how everything works after I work on it this weekend! Thanks and I'll keep you updated!

**Reply by onairmarc** [reply]
I got it working!! Thanks @jaydrogers for your help! For reference and for future people who need help, I'll include the Dockerfile and docker-compose.yml file below:

### Dockerfile
```dockerfile
FROM serversideup/php:8.3-fpm-nginx-alpine
LABEL authors="marcbeinder"

# Ensure we are running as root for package installations
USER root

# Install system dependencies and clear apk cache afterward
RUN apk update && apk add \
    git \
    curl \
    libpng-dev \
    oniguruma-dev \
    libxml2-dev \
    zip \
    unzip && \
    rm -rf /var/cache/apk/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Create the home directory for the user and set ownership
RUN mkdir -p /home/www-data/.composer && \
    chown -R www-data:www-data /home/www-data

# Set the working directory
WORKDIR /var/www

# Switch to non-root user after package installations
USER www-data

# Define the default command for PHP-FPM
CMD ["php-fpm"]
```

### docker-compose.yml
```yml
services:
    nginx:
        image: nginx:1.17-alpine
        container_name: epp-core-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./.config/nginx:/etc/nginx/conf.d
        networks:
            - epp-core-net

    app:
        build:
            args:
                userId: 1000
                groupId: 1000
            context: ./
            dockerfile: Dockerfile
        image: epp-core
        container_name: epp-core-app
        restart: unless-stopped
        stop_signal: SIGTERM
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - epp-core-net

    scheduler:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                userId: 1000
                groupId: 1000
        image: epp-core
        container_name: epp-core-scheduler
        restart: unless-stopped
        stop_signal: SIGTERM
        working_dir: /var/www/
        command: [ "php", "/var/www/artisan", "schedule:work" ]
        volumes:
            - ./:/var/www
        networks:
            - epp-core-net

    queue:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                userId: 1000
                groupId: 1000
        image: epp-core
        container_name: epp-core-queue
        restart: unless-stopped
        stop_signal: SIGTERM
        working_dir: /var/www/
        command: [ "php", "/var/www/artisan", "queue:work" ]
        volumes:
            - ./:/var/www
        networks:
            - epp-core-net

networks:
    epp-core-net:
        driver: bridge
```
