### DISCUSSION TITLE
Check shell scripts

### DISCUSSION THREAD

**Discussion by szepeviktor** [serversideup/docker-php#471] [Ideas & Feature Requests]
### Steps To Reproduce

Please use shellcheck on shell scripts.

### Host Operating System

Win95

**Comment by szepeviktor** [comment]
```yaml
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v4"
        -
            name: "Run ShellCheck"
            uses: "ludeeus/action-shellcheck@2.0.0"
```
