### DISCUSSION TITLE
Running Custom Script Failing When Not Local

### DISCUSSION THREAD

**Discussion by onairmarc** [serversideup/docker-php#480] [Q&A]
Hi All,

I've got a custom script that runs when the docker container starts. When I run the docker container locally, everything runs normally, but when I deploy the container to Digital Ocean, I get an error saying that the artisan file doesn't exist.

Below is the custom startup script with my debugging code commented out. This error occurs in both scenarios of the code being commented out and when the script runs fully.

The container starts up and runs perfectly fine when the shell script is not copied over, but without these commands running at startup, the system will never perform the necessary updates on deployment.

### 999-epp-startup.sh
```shell
#
# Copyright (c) 2024. Encore Digital Group.
# All Right Reserved.
#

echo "Upgrading EPP Core..."

# Store the current directory
#CURRENT_DIR=$(pwd)
#echo "Current Directory: $CURRENT_DIR"

# Change to the /var/www directory
#echo "Changing to /var/www"
#cd /var/www

# Verify the artisan file exists
if [ ! -f artisan ]; then
  echo "artisan file not found"
#  echo "artisan file not found in /var/www"
#  exit 1
fi

# Run the artisan commands
echo "Running Artisan Commands..."
php artisan migrate --force --isolated
php artisan epp:update

# Return to the original directory
#cd "$CURRENT_DIR"
#echo "Returned to $CURRENT_DIR"
```

### Dockerfile
```Dockerfile
FROM serversideup/php:8.3-fpm-nginx
LABEL authors="marcbeinder"

# Ensure we are running as root for package installations
USER root

ENV PHP_OPCACHE_ENABLE=1

COPY --chmod=755 .config/entrypoint.d/ /etc/entrypoint.d/

# Install system dependencies and clear apk cache afterward
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip && \
    apt-get clean

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Create the home directory for the user and set ownership
RUN mkdir -p /home/www-data/.composer && \
    chown -R www-data:www-data /home/www-data

# Set the working directory
WORKDIR /var/www

RUN rm -f  Dockerfile

# Switch to non-root user after package installations
USER www-data

# Define the default command for PHP-FPM
CMD ["php-fpm"]
```

### docker-compose.yml
```yml
services:
    nginx:
        image: nginx:1.17-alpine
        container_name: epp-core-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./.config/nginx:/etc/nginx/conf.d
        networks:
            - epp-core-net

    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: ghcr.io/encoredigitalgroup/epp-core
        container_name: epp-core-app
        restart: unless-stopped
        stop_signal: SIGTERM
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - epp-core-net

    scheduler:
        build:
            context: ./
            dockerfile: Dockerfile
        image: ghcr.io/encoredigitalgroup/epp-core
        container_name: epp-core-scheduler
        restart: unless-stopped
        stop_signal: SIGTERM
        working_dir: /var/www/
        command: [ "php", "/var/www/artisan", "schedule:work" ]
        volumes:
            - ./:/var/www
        networks:
            - epp-core-net

    queue:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                userId: 1000
                groupId: 1000
        image: ghcr.io/encoredigitalgroup/epp-core
        container_name: epp-core-queue
        restart: unless-stopped
        stop_signal: SIGTERM
        working_dir: /var/www/
        command: [ "php", "/var/www/artisan", "queue:work" ]
        volumes:
            - ./:/var/www
        networks:
            - epp-core-net

networks:
    epp-core-net:
        driver: bridge
```
