### DISCUSSION TITLE
Add tests

### DISCUSSION THREAD

**Discussion by jaydrogers** [serversideup/docker-php#67] [Ideas & Feature Requests]
# Summary
- It would be helpful to add tests

# Order
It would be nice to have each image go through these steps:
1. Setup (Pull base images & login to Docker)
2. Build
3. Test
4. Push

# What needs to be figured out yet
* What is the best way to "test" that PHP is working?
* Will it change on each deployment type (CLI, FPM, FPM-NGINX)

# Helpful resources
Here's some code that was provided by Github for reference:
```yaml
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  Push image to GitHub Packages.
  See also https://docs.docker.com/docker-hub/builds/
```

# Other notes
# Assertions
- [ ] PHP is the correct version

- [ ] Test that PHP is installed and the correct version:

    Create a simple PHP script that outputs the PHP version using phpinfo()
    Run it inside the container and assert the output is expected

- [ ] Test that your PHP extensions are enabled:

    Create a script that verifies certain extensions are loaded using extension_loaded()
    Assert that required extensions like mysqli, mbstring etc are present

- [ ] Test that Nginx is installed and running:

    Use curl to make a request to Nginx from inside the container
    Assert that it returns the expected response code and content

- [ ] Test PHP-FPM is running:

    Use ps aux to verify php-fpm process is running
    Make a PHP script that connects to php-fpm socket and handles a request
    Assert that it works correctly

- [ ] Test Nginx config is valid:

    Use nginx -t to check for valid config
    Assert no errors are thrown

- [ ] Test PHP loads under Nginx:

    Add a index.php script
    Curl the localhost and verify output
    Assert index.php is executed and not downloaded

# Example code
```yaml
name: Test PHP Image

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build image
      run: docker build . --file Dockerfile --tag my-php-image:latest

    - name: Test PHP version
      run: |
        docker run my-php-image php -v | grep "PHP 8.0"
    
    - name: Test extensions
      run: |
        docker run my-php-image php -m | grep mysqli
    
    - name: Test Nginx
      run: |
        docker run my-php-image curl http://localhost
    
    - name: Test php-fpm
      run: |
        docker run my-php-image ps aux | grep php-fpm

    - name: Test Nginx config
      run: |
        docker run my-php-image nginx -t
    
    - name: Test PHP with Nginx  
      run: |
        docker run my-php-image curl localhost | grep "Hello World"
      env:
        INDEX_SCRIPT: <?php echo "Hello World"; ?>
```
