### ISSUE TITLE
Wrong timezone in container even  PHP_DATE_TIMEZONE is set. 

### ISSUE THREAD

**Issue by M6268** [serversideup/docker-php#198]
### Affected Docker Images

serversideup/php:8.1-fpm-nginx-v2.2.1

### Current Behavior

environement variable PHP_DATE_TIMEZONE is not used by the image, it always stays as UTC

### Expected Behavior

timezone should follow PHP_DATE_TIMEZONE

### Steps To Reproduce

environment:
      PHP_MAX_EXECUTION_TIME : "300"
      PHP_MEMORY_LIMIT: "1024M"
      AUTORUN_ENABLED: false
      SSL_MODE: "off"
      PHP_DATE_TIMEZONE: "Asia/Riyadh"

### Host Operating System

Linux 5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Docker Version

```markdown
Client: Docker Engine - Community
 Version:           24.0.4
 API version:       1.43
 Go version:        go1.20.5
 Git commit:        3713ee1
 Built:             Fri Jul  7 14:50:57 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.4
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.5
  Git commit:       4ffc614
  Built:            Fri Jul  7 14:50:57 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by jaydrogers** [comment]
Unfortunately I am not able to replicate. You should check your PHP application to ensure it is respecting the timezone correctly.

### Sample Code to confirm
https://github.com/jaydrogers/docker-php-test-app/tree/timezone-test

### Actual Results
The timezone is being set correctly.
![Screenshot 2023-08-22 at 11 21 27@2x](https://github.com/serversideup/docker-php/assets/3174134/fcb18734-bac5-454f-a4b8-7c3489140001)

**Comment by M6268** [comment]
I am using a Dockerfile , is there anything wrong in my way of doing.

```
FROM serversideup/php:8.1-fpm-nginx-v2.2.1
LABEL maintainer="Manu KS"

RUN apt update && apt install tzdata -y
ENV TZ="Asia/Riyadh"

# Set working directory
WORKDIR /var/www/html

# Copy the application
COPY --chown=9999:9999 . /var/www/html

# Deployment steps
RUN composer install --optimize-autoloader --no-dev
```


docker-compose.yml

```
version: '3.7'

networks:
  web-dev:
  cloudflared:
    external: true

services:
  traefik:
    image: traefik:v2.10.3
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.traefik.address=:6268"
      - "--entrypoints.websecure.address=:443"
  php:
    build: .
    working_dir: /var/www/html
  
```


docker-compose.dev.yml

```
version: '3.7'
services:

  php:
    networks:
        - web-dev
    hostname: "intl-rech.localhost"
    volumes:
      - .:/var/www/html/:cached
    environment:
      PHP_MAX_EXECUTION_TIME : "300"
      PHP_MEMORY_LIMIT: "1024M"
      AUTORUN_ENABLED: false
      SSL_MODE: "off"
      PHP_DATE_TIMEZONE: "Asia/Riyadh"
    depends_on:
      - "traefik"
    ports:
      - 80:80
      - 443:443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`abc.domain.in`)"
      - "traefik.http.routers.php.entrypoints=web"
  traefik:
    networks:
      - web-dev
    ports:
      - 6268:6268
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=traefik"
      - "traefik.http.routers.traefik.service=api@internal"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    environment:
      PHP_DATE_TIMEZONE: "Asia/Riyadh"
```

**Comment by jaydrogers** [comment]
What happens when you do a PHP Info like I provided in my example code?

**Comment by jaydrogers** [comment]
The `date` command is from Ubuntu itself, not PHP.

So it's likely your PHP app is calling `date` and skipping the references from the PHP settings itself.

Try this in your **docker-compose.dev.yml**:

```yml
version: '3.7'
services:

  php:
    networks:
        - web-dev
    hostname: "intl-rech.localhost"
    volumes:
      - .:/var/www/html/:cached
    environment:
      PHP_MAX_EXECUTION_TIME : "300"
      PHP_MEMORY_LIMIT: "1024M"
      AUTORUN_ENABLED: false
      SSL_MODE: "off"
      PHP_DATE_TIMEZONE: "Asia/Riyadh"
      TZ: "Asia/Riyadh"
    depends_on:
      - "traefik"
    ports:
      - 80:80
      - 443:443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`abc.domain.in`)"
      - "traefik.http.routers.php.entrypoints=web"
  traefik:
    networks:
      - web-dev
    ports:
      - 6268:6268
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=traefik"
      - "traefik.http.routers.traefik.service=api@internal"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
```

In the example above, I am having Docker Compose set the `TZ` variable instead of you doing it in a Dockerfile (reference https://tecadmin.net/change-timezone-in-docker-container/)
