### ISSUE TITLE
Check shell scripts

### ISSUE THREAD

**Issue by szepeviktor** [serversideup/docker-php#333]
### Affected Docker Images

all

### Current Behavior

unknown errros

### Expected Behavior

no errors!

### Steps To Reproduce

Please use shellcheck on shell scripts.

### Host Operating System

Win95

### Docker Version

```markdown
-
```

**Comment by szepeviktor** [comment]
```yaml
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v4.1.5"
        -
            name: "Run ShellCheck"
            uses: "ludeeus/action-shellcheck@2.0.0"
```
