### ISSUE TITLE
Create native healthchecks for advanced Laravel services

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#444]
# ‼️ Problem
- Writing health checks in Docker containers is annoying, and can be complicated syntax
- Some Laravel services don't have Healthchecks built into them (ie. queues)

### Examples
- https://github.com/serversideup/docker-php/issues/391

# 👉 Proposed solution
The following could resolve this issue:

### Create predefined health checks at `/healthchecks`
We would create health checks for each service:
- [x] Laravel Horizon
- [x] Laravel Queues
- [x] Laravel Reverb
- [x] Laravel Task Scheduler

### Create scripts for each service
Laravel Horizon has `php artisan horizon:status`, but other services do not have this. We could use `pgrep` to see if the script is running:

```bash
#!/bin/sh

# Use pgrep which is more consistent across distributions
if pgrep -f "php artisan queue:work" > /dev/null
then
    exit 0
else
    exit 1
fi
```

### Example health check
Once this is developed, an example Docker Compose file would look like:

```yaml
services:
  php:
    image: my/laravel-app

  queue:
    image: my/laravel-app
    command: ["php", "/var/www/html/artisan", "queue:work", "--tries=3"]
    healthcheck:
       test: ["CMD", "/healthchecks/queue"]
       interval: 10s
       timeout: 5s
       retries: 3

```

# 🗣️ Further discussion
1. Do you like having everyhing in the `/healthchecks` folder?
2. Is our "definition of healthy" good enough by just checking the process? Or is it too hacky?

Would love to hear the perspective from the brilliant @nckrtl if he has any time to chime in 🤓
