### ISSUE TITLE
Simple docker compose up delivers 404

### ISSUE THREAD

**Issue by damanic** [serversideup/docker-php#53]
### Current Behavior

Accessing the service over exposed port from host results in 404 file not found error, regardless of files present in the docker containers `/var/www/html/` directory.

### Expected Behavior

Accessing the service over exposed port from host should serve files present in the docker containers `/var/www/html/` directory.

### Steps To Reproduce

1. Host environment: Windows 10+ .  Testing access without valid SSL certificate.
2. The following compose

```
version: '3.7'
services:
  php:
    image: serversideup/php:7.4-fpm-nginx
    restart: always
    ports:
      - "8023:80"
      - "8448:443"
    volumes:
      - ./public/:/var/www/html/
```
3. Run `docker compose up --build` 
4. Place index.php [phpinfo()] in container volume ` ./public/:/var/www/html/` and access via https://localhost:8448

Expected result = 200 phpinfo() output
Actual result = 404 file not found

Screenshot of 404 response served by container:
![image](https://user-images.githubusercontent.com/5227303/158043314-469411db-93c6-45dd-83cf-46884ec21e91.png)

Screenshot of file present in the container   `/var/www/html/`  directory
![image](https://user-images.githubusercontent.com/5227303/158043345-2166fc1f-27b7-4a01-b189-dc34e0d7616c.png)

### Host Operating System

Windows 10

### Docker Version

```markdown
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:44:07 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.5.1 (74721)
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```


### Anything else?

_No response_

**Comment by damanic** [comment]
Ah I see what I have done.

Files are served from `/var/www/html/public`

Correct compose is:

```
version: '3.7'
services:
  php:
    image: serversideup/php:7.4-fpm-nginx
    restart: always
    ports:
      - "8023:80"
      - "8448:443"
    volumes:
      - ./public/:/var/www/html/public
      
```

Perhaps the README on this repo should include something like this simple docker compose example.
